import type { Metadata } from "next";
import type { Viewport } from 'next'
import { Inter } from "next/font/google";
import "./globals.css";
import Header from './header';
import Footer from "./footer";
import Stack from '@mui/material/Stack';
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">

      <body style={{
        padding: 0,
        margin: 0,
      }} >

        <Header />

        <Box sx={{
          marginTop: '30px',
          marginBottom: '100px'
        }}>
          {children}
        </Box>

        <Footer />

      </body>

    </html>
  );
}
